/*
 * v1alpha1/cleanup.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1CleanupPreview struct {
	OrphanedRepos         []V1alpha1OrphanedRepo `json:"orphanedRepos,omitempty"`
	OrphanedLfsObjects    []V1alpha1OrphanedLfs  `json:"orphanedLfsObjects,omitempty"`
	TotalReclaimableBytes string                 `json:"totalReclaimableBytes,omitempty"`
}
