/*
 * v1alpha1/cleanup.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1ExecuteCleanupRequest struct {
	CleanOrphanedRepos bool `json:"cleanOrphanedRepos,omitempty"`
	CleanOrphanedLfs   bool `json:"cleanOrphanedLfs,omitempty"`
	DryRun             bool `json:"dryRun,omitempty"`
}
