/*
 * v1alpha1/cleanup.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1StorageStats struct {
	TotalSizeBytes        string `json:"totalSizeBytes,omitempty"`
	RepositoriesSizeBytes string `json:"repositoriesSizeBytes,omitempty"`
	LfsSizeBytes          string `json:"lfsSizeBytes,omitempty"`
	OrphanedSizeBytes     string `json:"orphanedSizeBytes,omitempty"`
}
