/*
 * v1alpha1/cleanup.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1PreviewCleanupRequest struct {
	IncludeOrphanedRepos bool `json:"includeOrphanedRepos,omitempty"`
	IncludeOrphanedLfs   bool `json:"includeOrphanedLfs,omitempty"`
}
