// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: v1alpha1/project.proto

package v1alpha1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectType int32

const (
	ProjectType_PROJECT_TYPE_UNSPECIFIED ProjectType = 0
	ProjectType_PROJECT_TYPE_PRIVATE     ProjectType = 1
	ProjectType_PROJECT_TYPE_PUBLIC      ProjectType = 2
)

// Enum value maps for ProjectType.
var (
	ProjectType_name = map[int32]string{
		0: "PROJECT_TYPE_UNSPECIFIED",
		1: "PROJECT_TYPE_PRIVATE",
		2: "PROJECT_TYPE_PUBLIC",
	}
	ProjectType_value = map[string]int32{
		"PROJECT_TYPE_UNSPECIFIED": 0,
		"PROJECT_TYPE_PRIVATE":     1,
		"PROJECT_TYPE_PUBLIC":      2,
	}
)

func (x ProjectType) Enum() *ProjectType {
	p := new(ProjectType)
	*p = x
	return p
}

func (x ProjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_project_proto_enumTypes[0].Descriptor()
}

func (ProjectType) Type() protoreflect.EnumType {
	return &file_v1alpha1_project_proto_enumTypes[0]
}

func (x ProjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectType.Descriptor instead.
func (ProjectType) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{0}
}

// ProjectPermissionFilter controls which projects are returned based on user permissions.
// Wire values are backward compatible with the old bool managed_only field (false=0, true=1).
type ProjectPermissionFilter int32

const (
	// Default: returns accessible projects + public projects (compatible with old managed_only=false)
	ProjectPermissionFilter_PERMISSION_FILTER_UNSPECIFIED ProjectPermissionFilter = 0
	// Returns only explicitly authorized projects, excluding public (compatible with old managed_only=true)
	ProjectPermissionFilter_PERMISSION_FILTER_MANAGED_ONLY ProjectPermissionFilter = 1
	// Returns only projects where user has write permission (model.push or dataset.push)
	ProjectPermissionFilter_PERMISSION_FILTER_CAN_WRITE ProjectPermissionFilter = 2
	// Returns projects where user has read permission + public projects
	ProjectPermissionFilter_PERMISSION_FILTER_CAN_READ ProjectPermissionFilter = 3
)

// Enum value maps for ProjectPermissionFilter.
var (
	ProjectPermissionFilter_name = map[int32]string{
		0: "PERMISSION_FILTER_UNSPECIFIED",
		1: "PERMISSION_FILTER_MANAGED_ONLY",
		2: "PERMISSION_FILTER_CAN_WRITE",
		3: "PERMISSION_FILTER_CAN_READ",
	}
	ProjectPermissionFilter_value = map[string]int32{
		"PERMISSION_FILTER_UNSPECIFIED":  0,
		"PERMISSION_FILTER_MANAGED_ONLY": 1,
		"PERMISSION_FILTER_CAN_WRITE":    2,
		"PERMISSION_FILTER_CAN_READ":     3,
	}
)

func (x ProjectPermissionFilter) Enum() *ProjectPermissionFilter {
	p := new(ProjectPermissionFilter)
	*p = x
	return p
}

func (x ProjectPermissionFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectPermissionFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_project_proto_enumTypes[1].Descriptor()
}

func (ProjectPermissionFilter) Type() protoreflect.EnumType {
	return &file_v1alpha1_project_proto_enumTypes[1]
}

func (x ProjectPermissionFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectPermissionFilter.Descriptor instead.
func (ProjectPermissionFilter) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{1}
}

type MemberType int32

const (
	MemberType_MEMBER_TYPE_USER  MemberType = 0
	MemberType_MEMBER_TYPE_GROUP MemberType = 1
)

// Enum value maps for MemberType.
var (
	MemberType_name = map[int32]string{
		0: "MEMBER_TYPE_USER",
		1: "MEMBER_TYPE_GROUP",
	}
	MemberType_value = map[string]int32{
		"MEMBER_TYPE_USER":  0,
		"MEMBER_TYPE_GROUP": 1,
	}
)

func (x MemberType) Enum() *MemberType {
	p := new(MemberType)
	*p = x
	return p
}

func (x MemberType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_project_proto_enumTypes[2].Descriptor()
}

func (MemberType) Type() protoreflect.EnumType {
	return &file_v1alpha1_project_proto_enumTypes[2]
}

func (x MemberType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberType.Descriptor instead.
func (MemberType) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{2}
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          ProjectType            `protobuf:"varint,2,opt,name=type,proto3,enum=matrixhub.v1alpha1.ProjectType" json:"type,omitempty"`
	RegistryId    *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=registry_id,json=registryId,proto3" json:"registry_id,omitempty"`
	Organization  string                 `protobuf:"bytes,4,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_v1alpha1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetType() ProjectType {
	if x != nil {
		return x.Type
	}
	return ProjectType_PROJECT_TYPE_UNSPECIFIED
}

func (x *CreateProjectRequest) GetRegistryId() *wrapperspb.Int32Value {
	if x != nil {
		return x.RegistryId
	}
	return nil
}

func (x *CreateProjectRequest) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_v1alpha1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{1}
}

type ListProjectsRequest struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Name             string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type             ProjectType             `protobuf:"varint,2,opt,name=type,proto3,enum=matrixhub.v1alpha1.ProjectType" json:"type,omitempty"`
	PermissionFilter ProjectPermissionFilter `protobuf:"varint,3,opt,name=permission_filter,json=permissionFilter,proto3,enum=matrixhub.v1alpha1.ProjectPermissionFilter" json:"permission_filter,omitempty"`
	Page             int32                   `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int32                   `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_v1alpha1_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{2}
}

func (x *ListProjectsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListProjectsRequest) GetType() ProjectType {
	if x != nil {
		return x.Type
	}
	return ProjectType_PROJECT_TYPE_UNSPECIFIED
}

func (x *ListProjectsRequest) GetPermissionFilter() ProjectPermissionFilter {
	if x != nil {
		return x.PermissionFilter
	}
	return ProjectPermissionFilter_PERMISSION_FILTER_UNSPECIFIED
}

func (x *ListProjectsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProjectsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_v1alpha1_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{3}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ListProjectsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_v1alpha1_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{4}
}

func (x *GetProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          ProjectType            `protobuf:"varint,2,opt,name=type,proto3,enum=matrixhub.v1alpha1.ProjectType" json:"type,omitempty"`
	RegistryUrl   string                 `protobuf:"bytes,3,opt,name=registry_url,json=registryUrl,proto3" json:"registry_url,omitempty"`
	Organization  string                 `protobuf:"bytes,4,opt,name=organization,proto3" json:"organization,omitempty"`
	ModelCount    uint32                 `protobuf:"varint,5,opt,name=model_count,json=modelCount,proto3" json:"model_count,omitempty"`
	DatasetCount  uint32                 `protobuf:"varint,6,opt,name=dataset_count,json=datasetCount,proto3" json:"dataset_count,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectResponse) Reset() {
	*x = GetProjectResponse{}
	mi := &file_v1alpha1_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectResponse) ProtoMessage() {}

func (x *GetProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectResponse.ProtoReflect.Descriptor instead.
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{5}
}

func (x *GetProjectResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProjectResponse) GetType() ProjectType {
	if x != nil {
		return x.Type
	}
	return ProjectType_PROJECT_TYPE_UNSPECIFIED
}

func (x *GetProjectResponse) GetRegistryUrl() string {
	if x != nil {
		return x.RegistryUrl
	}
	return ""
}

func (x *GetProjectResponse) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *GetProjectResponse) GetModelCount() uint32 {
	if x != nil {
		return x.ModelCount
	}
	return 0
}

func (x *GetProjectResponse) GetDatasetCount() uint32 {
	if x != nil {
		return x.DatasetCount
	}
	return 0
}

func (x *GetProjectResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_v1alpha1_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectResponse) Reset() {
	*x = DeleteProjectResponse{}
	mi := &file_v1alpha1_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectResponse) ProtoMessage() {}

func (x *DeleteProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{7}
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          ProjectType            `protobuf:"varint,2,opt,name=type,proto3,enum=matrixhub.v1alpha1.ProjectType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_v1alpha1_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProjectRequest) GetType() ProjectType {
	if x != nil {
		return x.Type
	}
	return ProjectType_PROJECT_TYPE_UNSPECIFIED
}

type UpdateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectResponse) Reset() {
	*x = UpdateProjectResponse{}
	mi := &file_v1alpha1_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectResponse) ProtoMessage() {}

func (x *UpdateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectResponse.ProtoReflect.Descriptor instead.
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{9}
}

type Project struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type            ProjectType            `protobuf:"varint,2,opt,name=type,proto3,enum=matrixhub.v1alpha1.ProjectType" json:"type,omitempty"`
	EnabledRegistry bool                   `protobuf:"varint,3,opt,name=enabled_registry,json=enabledRegistry,proto3" json:"enabled_registry,omitempty"`
	ModelCount      uint32                 `protobuf:"varint,4,opt,name=model_count,json=modelCount,proto3" json:"model_count,omitempty"`
	DatasetCount    uint32                 `protobuf:"varint,5,opt,name=dataset_count,json=datasetCount,proto3" json:"dataset_count,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_v1alpha1_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{10}
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetType() ProjectType {
	if x != nil {
		return x.Type
	}
	return ProjectType_PROJECT_TYPE_UNSPECIFIED
}

func (x *Project) GetEnabledRegistry() bool {
	if x != nil {
		return x.EnabledRegistry
	}
	return false
}

func (x *Project) GetModelCount() uint32 {
	if x != nil {
		return x.ModelCount
	}
	return 0
}

func (x *Project) GetDatasetCount() uint32 {
	if x != nil {
		return x.DatasetCount
	}
	return 0
}

func (x *Project) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListProjectMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MemberName    string                 `protobuf:"bytes,2,opt,name=member_name,json=memberName,proto3" json:"member_name,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectMembersRequest) Reset() {
	*x = ListProjectMembersRequest{}
	mi := &file_v1alpha1_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectMembersRequest) ProtoMessage() {}

func (x *ListProjectMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectMembersRequest.ProtoReflect.Descriptor instead.
func (*ListProjectMembersRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{11}
}

func (x *ListProjectMembersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListProjectMembersRequest) GetMemberName() string {
	if x != nil {
		return x.MemberName
	}
	return ""
}

func (x *ListProjectMembersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProjectMembersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListProjectMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*ProjectMember       `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectMembersResponse) Reset() {
	*x = ListProjectMembersResponse{}
	mi := &file_v1alpha1_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectMembersResponse) ProtoMessage() {}

func (x *ListProjectMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectMembersResponse.ProtoReflect.Descriptor instead.
func (*ListProjectMembersResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{12}
}

func (x *ListProjectMembersResponse) GetMembers() []*ProjectMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListProjectMembersResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ProjectMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      int32                  `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	MemberName    string                 `protobuf:"bytes,2,opt,name=member_name,json=memberName,proto3" json:"member_name,omitempty"`
	MemberType    MemberType             `protobuf:"varint,3,opt,name=member_type,json=memberType,proto3,enum=matrixhub.v1alpha1.MemberType" json:"member_type,omitempty"`
	Role          ProjectRoleType        `protobuf:"varint,4,opt,name=role,proto3,enum=matrixhub.v1alpha1.ProjectRoleType" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMember) Reset() {
	*x = ProjectMember{}
	mi := &file_v1alpha1_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMember) ProtoMessage() {}

func (x *ProjectMember) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMember.ProtoReflect.Descriptor instead.
func (*ProjectMember) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{13}
}

func (x *ProjectMember) GetMemberId() int32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *ProjectMember) GetMemberName() string {
	if x != nil {
		return x.MemberName
	}
	return ""
}

func (x *ProjectMember) GetMemberType() MemberType {
	if x != nil {
		return x.MemberType
	}
	return MemberType_MEMBER_TYPE_USER
}

func (x *ProjectMember) GetRole() ProjectRoleType {
	if x != nil {
		return x.Role
	}
	return ProjectRoleType_ROLE_TYPE_PROJECT_ADMIN
}

type AddProjectMemberWithRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MemberType    MemberType             `protobuf:"varint,2,opt,name=member_type,json=memberType,proto3,enum=matrixhub.v1alpha1.MemberType" json:"member_type,omitempty"`
	MemberId      int32                  `protobuf:"varint,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Role          ProjectRoleType        `protobuf:"varint,4,opt,name=role,proto3,enum=matrixhub.v1alpha1.ProjectRoleType" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProjectMemberWithRoleRequest) Reset() {
	*x = AddProjectMemberWithRoleRequest{}
	mi := &file_v1alpha1_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProjectMemberWithRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProjectMemberWithRoleRequest) ProtoMessage() {}

func (x *AddProjectMemberWithRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProjectMemberWithRoleRequest.ProtoReflect.Descriptor instead.
func (*AddProjectMemberWithRoleRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{14}
}

func (x *AddProjectMemberWithRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProjectMemberWithRoleRequest) GetMemberType() MemberType {
	if x != nil {
		return x.MemberType
	}
	return MemberType_MEMBER_TYPE_USER
}

func (x *AddProjectMemberWithRoleRequest) GetMemberId() int32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *AddProjectMemberWithRoleRequest) GetRole() ProjectRoleType {
	if x != nil {
		return x.Role
	}
	return ProjectRoleType_ROLE_TYPE_PROJECT_ADMIN
}

type AddProjectMemberWithRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProjectMemberWithRoleResponse) Reset() {
	*x = AddProjectMemberWithRoleResponse{}
	mi := &file_v1alpha1_project_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProjectMemberWithRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProjectMemberWithRoleResponse) ProtoMessage() {}

func (x *AddProjectMemberWithRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProjectMemberWithRoleResponse.ProtoReflect.Descriptor instead.
func (*AddProjectMemberWithRoleResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{15}
}

type RemoveProjectMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Members       []*MemberToRemove      `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProjectMembersRequest) Reset() {
	*x = RemoveProjectMembersRequest{}
	mi := &file_v1alpha1_project_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProjectMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProjectMembersRequest) ProtoMessage() {}

func (x *RemoveProjectMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProjectMembersRequest.ProtoReflect.Descriptor instead.
func (*RemoveProjectMembersRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveProjectMembersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoveProjectMembersRequest) GetMembers() []*MemberToRemove {
	if x != nil {
		return x.Members
	}
	return nil
}

type MemberToRemove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberType    MemberType             `protobuf:"varint,1,opt,name=member_type,json=memberType,proto3,enum=matrixhub.v1alpha1.MemberType" json:"member_type,omitempty"`
	MemberId      int32                  `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberToRemove) Reset() {
	*x = MemberToRemove{}
	mi := &file_v1alpha1_project_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberToRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberToRemove) ProtoMessage() {}

func (x *MemberToRemove) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberToRemove.ProtoReflect.Descriptor instead.
func (*MemberToRemove) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{17}
}

func (x *MemberToRemove) GetMemberType() MemberType {
	if x != nil {
		return x.MemberType
	}
	return MemberType_MEMBER_TYPE_USER
}

func (x *MemberToRemove) GetMemberId() int32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

type RemoveProjectMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProjectMembersResponse) Reset() {
	*x = RemoveProjectMembersResponse{}
	mi := &file_v1alpha1_project_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProjectMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProjectMembersResponse) ProtoMessage() {}

func (x *RemoveProjectMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProjectMembersResponse.ProtoReflect.Descriptor instead.
func (*RemoveProjectMembersResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{18}
}

type UpdateProjectMemberRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MemberType    MemberType             `protobuf:"varint,2,opt,name=member_type,json=memberType,proto3,enum=matrixhub.v1alpha1.MemberType" json:"member_type,omitempty"`
	MemberId      int32                  `protobuf:"varint,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Role          ProjectRoleType        `protobuf:"varint,4,opt,name=role,proto3,enum=matrixhub.v1alpha1.ProjectRoleType" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectMemberRoleRequest) Reset() {
	*x = UpdateProjectMemberRoleRequest{}
	mi := &file_v1alpha1_project_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectMemberRoleRequest) ProtoMessage() {}

func (x *UpdateProjectMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateProjectMemberRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProjectMemberRoleRequest) GetMemberType() MemberType {
	if x != nil {
		return x.MemberType
	}
	return MemberType_MEMBER_TYPE_USER
}

func (x *UpdateProjectMemberRoleRequest) GetMemberId() int32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *UpdateProjectMemberRoleRequest) GetRole() ProjectRoleType {
	if x != nil {
		return x.Role
	}
	return ProjectRoleType_ROLE_TYPE_PROJECT_ADMIN
}

type UpdateProjectMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectMemberRoleResponse) Reset() {
	*x = UpdateProjectMemberRoleResponse{}
	mi := &file_v1alpha1_project_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectMemberRoleResponse) ProtoMessage() {}

func (x *UpdateProjectMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateProjectMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{20}
}

var File_v1alpha1_project_proto protoreflect.FileDescriptor

const file_v1alpha1_project_proto_rawDesc = "" +
	"\n" +
	"\x16v1alpha1/project.proto\x12\x12matrixhub.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\x1a\x13v1alpha1/role.proto\x1a\x14v1alpha1/utils.proto\"\xfd\x01\n" +
	"\x14CreateProjectRequest\x12B\n" +
	"\x04name\x18\x01 \x01(\tB.\xfaB+r)\x10\x022%^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$R\x04name\x12?\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.matrixhub.v1alpha1.ProjectTypeB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\x04type\x12<\n" +
	"\vregistry_id\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"registryId\x12\"\n" +
	"\forganization\x18\x04 \x01(\tR\forganization\"\x17\n" +
	"\x15CreateProjectResponse\"\xe9\x01\n" +
	"\x13ListProjectsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.matrixhub.v1alpha1.ProjectTypeR\x04type\x12X\n" +
	"\x11permission_filter\x18\x03 \x01(\x0e2+.matrixhub.v1alpha1.ProjectPermissionFilterR\x10permissionFilter\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\x8f\x01\n" +
	"\x14ListProjectsResponse\x127\n" +
	"\bprojects\x18\x01 \x03(\v2\x1b.matrixhub.v1alpha1.ProjectR\bprojects\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.matrixhub.v1alpha1.PaginationR\n" +
	"pagination\"0\n" +
	"\x11GetProjectRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\"\xa5\x02\n" +
	"\x12GetProjectResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.matrixhub.v1alpha1.ProjectTypeR\x04type\x12!\n" +
	"\fregistry_url\x18\x03 \x01(\tR\vregistryUrl\x12\"\n" +
	"\forganization\x18\x04 \x01(\tR\forganization\x12\x1f\n" +
	"\vmodel_count\x18\x05 \x01(\rR\n" +
	"modelCount\x12#\n" +
	"\rdataset_count\x18\x06 \x01(\rR\fdatasetCount\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"3\n" +
	"\x14DeleteProjectRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\"\x17\n" +
	"\x15DeleteProjectResponse\"h\n" +
	"\x14UpdateProjectRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.matrixhub.v1alpha1.ProjectTypeR\x04type\"\x17\n" +
	"\x15UpdateProjectResponse\"\xfe\x01\n" +
	"\aProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.matrixhub.v1alpha1.ProjectTypeR\x04type\x12)\n" +
	"\x10enabled_registry\x18\x03 \x01(\bR\x0fenabledRegistry\x12\x1f\n" +
	"\vmodel_count\x18\x04 \x01(\rR\n" +
	"modelCount\x12#\n" +
	"\rdataset_count\x18\x05 \x01(\rR\fdatasetCount\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8a\x01\n" +
	"\x19ListProjectMembersRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12\x1f\n" +
	"\vmember_name\x18\x02 \x01(\tR\n" +
	"memberName\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x99\x01\n" +
	"\x1aListProjectMembersResponse\x12;\n" +
	"\amembers\x18\x01 \x03(\v2!.matrixhub.v1alpha1.ProjectMemberR\amembers\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.matrixhub.v1alpha1.PaginationR\n" +
	"pagination\"\xc7\x01\n" +
	"\rProjectMember\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x05R\bmemberId\x12\x1f\n" +
	"\vmember_name\x18\x02 \x01(\tR\n" +
	"memberName\x12?\n" +
	"\vmember_type\x18\x03 \x01(\x0e2\x1e.matrixhub.v1alpha1.MemberTypeR\n" +
	"memberType\x127\n" +
	"\x04role\x18\x04 \x01(\x0e2#.matrixhub.v1alpha1.ProjectRoleTypeR\x04role\"\xf2\x01\n" +
	"\x1fAddProjectMemberWithRoleRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12I\n" +
	"\vmember_type\x18\x02 \x01(\x0e2\x1e.matrixhub.v1alpha1.MemberTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\n" +
	"memberType\x12$\n" +
	"\tmember_id\x18\x03 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\bmemberId\x12A\n" +
	"\x04role\x18\x04 \x01(\x0e2#.matrixhub.v1alpha1.ProjectRoleTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\x04role\"\"\n" +
	" AddProjectMemberWithRoleResponse\"x\n" +
	"\x1bRemoveProjectMembersRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12<\n" +
	"\amembers\x18\x02 \x03(\v2\".matrixhub.v1alpha1.MemberToRemoveR\amembers\"\x81\x01\n" +
	"\x0eMemberToRemove\x12I\n" +
	"\vmember_type\x18\x01 \x01(\x0e2\x1e.matrixhub.v1alpha1.MemberTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\n" +
	"memberType\x12$\n" +
	"\tmember_id\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\bmemberId\"\x1e\n" +
	"\x1cRemoveProjectMembersResponse\"\xf1\x01\n" +
	"\x1eUpdateProjectMemberRoleRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12I\n" +
	"\vmember_type\x18\x02 \x01(\x0e2\x1e.matrixhub.v1alpha1.MemberTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\n" +
	"memberType\x12$\n" +
	"\tmember_id\x18\x03 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\bmemberId\x12A\n" +
	"\x04role\x18\x04 \x01(\x0e2#.matrixhub.v1alpha1.ProjectRoleTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\x04role\"!\n" +
	"\x1fUpdateProjectMemberRoleResponse*^\n" +
	"\vProjectType\x12\x1c\n" +
	"\x18PROJECT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROJECT_TYPE_PRIVATE\x10\x01\x12\x17\n" +
	"\x13PROJECT_TYPE_PUBLIC\x10\x02*\xa1\x01\n" +
	"\x17ProjectPermissionFilter\x12!\n" +
	"\x1dPERMISSION_FILTER_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1ePERMISSION_FILTER_MANAGED_ONLY\x10\x01\x12\x1f\n" +
	"\x1bPERMISSION_FILTER_CAN_WRITE\x10\x02\x12\x1e\n" +
	"\x1aPERMISSION_FILTER_CAN_READ\x10\x03*9\n" +
	"\n" +
	"MemberType\x12\x14\n" +
	"\x10MEMBER_TYPE_USER\x10\x00\x12\x15\n" +
	"\x11MEMBER_TYPE_GROUP\x10\x012\x91\v\n" +
	"\bProjects\x12\x87\x01\n" +
	"\rCreateProject\x12(.matrixhub.v1alpha1.CreateProjectRequest\x1a).matrixhub.v1alpha1.CreateProjectResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1alpha1/projects\x12\x81\x01\n" +
	"\fListProjects\x12'.matrixhub.v1alpha1.ListProjectsRequest\x1a(.matrixhub.v1alpha1.ListProjectsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1alpha1/projects\x12\x82\x01\n" +
	"\n" +
	"GetProject\x12%.matrixhub.v1alpha1.GetProjectRequest\x1a&.matrixhub.v1alpha1.GetProjectResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1alpha1/projects/{name}\x12\x8e\x01\n" +
	"\rUpdateProject\x12(.matrixhub.v1alpha1.UpdateProjectRequest\x1a).matrixhub.v1alpha1.UpdateProjectResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\x1a\x1d/api/v1alpha1/projects/{name}\x12\x8b\x01\n" +
	"\rDeleteProject\x12(.matrixhub.v1alpha1.DeleteProjectRequest\x1a).matrixhub.v1alpha1.DeleteProjectResponse\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/api/v1alpha1/projects/{name}\x12\xa2\x01\n" +
	"\x12ListProjectMembers\x12-.matrixhub.v1alpha1.ListProjectMembersRequest\x1a..matrixhub.v1alpha1.ListProjectMembersResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/v1alpha1/projects/{name}/members\x12\xb7\x01\n" +
	"\x18AddProjectMemberWithRole\x123.matrixhub.v1alpha1.AddProjectMemberWithRoleRequest\x1a4.matrixhub.v1alpha1.AddProjectMemberWithRoleResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/api/v1alpha1/projects/{name}/members\x12\xab\x01\n" +
	"\x14RemoveProjectMembers\x12/.matrixhub.v1alpha1.RemoveProjectMembersRequest\x1a0.matrixhub.v1alpha1.RemoveProjectMembersResponse\"0\x82\xd3\xe4\x93\x02*:\x01**%/api/v1alpha1/projects/{name}/members\x12\xc5\x01\n" +
	"\x17UpdateProjectMemberRole\x122.matrixhub.v1alpha1.UpdateProjectMemberRoleRequest\x1a3.matrixhub.v1alpha1.UpdateProjectMemberRoleResponse\"A\x82\xd3\xe4\x93\x02;:\x01*\x1a6/api/v1alpha1/projects/{name}/members/{member_id}/roleB<Z:github.com/matrixhub-ai/matrixhub/api/go/v1alpha1;v1alpha1b\x06proto3"

var (
	file_v1alpha1_project_proto_rawDescOnce sync.Once
	file_v1alpha1_project_proto_rawDescData []byte
)

func file_v1alpha1_project_proto_rawDescGZIP() []byte {
	file_v1alpha1_project_proto_rawDescOnce.Do(func() {
		file_v1alpha1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_project_proto_rawDesc), len(file_v1alpha1_project_proto_rawDesc)))
	})
	return file_v1alpha1_project_proto_rawDescData
}

var file_v1alpha1_project_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_v1alpha1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_v1alpha1_project_proto_goTypes = []any{
	(ProjectType)(0),                         // 0: matrixhub.v1alpha1.ProjectType
	(ProjectPermissionFilter)(0),             // 1: matrixhub.v1alpha1.ProjectPermissionFilter
	(MemberType)(0),                          // 2: matrixhub.v1alpha1.MemberType
	(*CreateProjectRequest)(nil),             // 3: matrixhub.v1alpha1.CreateProjectRequest
	(*CreateProjectResponse)(nil),            // 4: matrixhub.v1alpha1.CreateProjectResponse
	(*ListProjectsRequest)(nil),              // 5: matrixhub.v1alpha1.ListProjectsRequest
	(*ListProjectsResponse)(nil),             // 6: matrixhub.v1alpha1.ListProjectsResponse
	(*GetProjectRequest)(nil),                // 7: matrixhub.v1alpha1.GetProjectRequest
	(*GetProjectResponse)(nil),               // 8: matrixhub.v1alpha1.GetProjectResponse
	(*DeleteProjectRequest)(nil),             // 9: matrixhub.v1alpha1.DeleteProjectRequest
	(*DeleteProjectResponse)(nil),            // 10: matrixhub.v1alpha1.DeleteProjectResponse
	(*UpdateProjectRequest)(nil),             // 11: matrixhub.v1alpha1.UpdateProjectRequest
	(*UpdateProjectResponse)(nil),            // 12: matrixhub.v1alpha1.UpdateProjectResponse
	(*Project)(nil),                          // 13: matrixhub.v1alpha1.Project
	(*ListProjectMembersRequest)(nil),        // 14: matrixhub.v1alpha1.ListProjectMembersRequest
	(*ListProjectMembersResponse)(nil),       // 15: matrixhub.v1alpha1.ListProjectMembersResponse
	(*ProjectMember)(nil),                    // 16: matrixhub.v1alpha1.ProjectMember
	(*AddProjectMemberWithRoleRequest)(nil),  // 17: matrixhub.v1alpha1.AddProjectMemberWithRoleRequest
	(*AddProjectMemberWithRoleResponse)(nil), // 18: matrixhub.v1alpha1.AddProjectMemberWithRoleResponse
	(*RemoveProjectMembersRequest)(nil),      // 19: matrixhub.v1alpha1.RemoveProjectMembersRequest
	(*MemberToRemove)(nil),                   // 20: matrixhub.v1alpha1.MemberToRemove
	(*RemoveProjectMembersResponse)(nil),     // 21: matrixhub.v1alpha1.RemoveProjectMembersResponse
	(*UpdateProjectMemberRoleRequest)(nil),   // 22: matrixhub.v1alpha1.UpdateProjectMemberRoleRequest
	(*UpdateProjectMemberRoleResponse)(nil),  // 23: matrixhub.v1alpha1.UpdateProjectMemberRoleResponse
	(*wrapperspb.Int32Value)(nil),            // 24: google.protobuf.Int32Value
	(*Pagination)(nil),                       // 25: matrixhub.v1alpha1.Pagination
	(*timestamppb.Timestamp)(nil),            // 26: google.protobuf.Timestamp
	(ProjectRoleType)(0),                     // 27: matrixhub.v1alpha1.ProjectRoleType
}
var file_v1alpha1_project_proto_depIdxs = []int32{
	0,  // 0: matrixhub.v1alpha1.CreateProjectRequest.type:type_name -> matrixhub.v1alpha1.ProjectType
	24, // 1: matrixhub.v1alpha1.CreateProjectRequest.registry_id:type_name -> google.protobuf.Int32Value
	0,  // 2: matrixhub.v1alpha1.ListProjectsRequest.type:type_name -> matrixhub.v1alpha1.ProjectType
	1,  // 3: matrixhub.v1alpha1.ListProjectsRequest.permission_filter:type_name -> matrixhub.v1alpha1.ProjectPermissionFilter
	13, // 4: matrixhub.v1alpha1.ListProjectsResponse.projects:type_name -> matrixhub.v1alpha1.Project
	25, // 5: matrixhub.v1alpha1.ListProjectsResponse.pagination:type_name -> matrixhub.v1alpha1.Pagination
	0,  // 6: matrixhub.v1alpha1.GetProjectResponse.type:type_name -> matrixhub.v1alpha1.ProjectType
	26, // 7: matrixhub.v1alpha1.GetProjectResponse.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: matrixhub.v1alpha1.UpdateProjectRequest.type:type_name -> matrixhub.v1alpha1.ProjectType
	0,  // 9: matrixhub.v1alpha1.Project.type:type_name -> matrixhub.v1alpha1.ProjectType
	26, // 10: matrixhub.v1alpha1.Project.updated_at:type_name -> google.protobuf.Timestamp
	16, // 11: matrixhub.v1alpha1.ListProjectMembersResponse.members:type_name -> matrixhub.v1alpha1.ProjectMember
	25, // 12: matrixhub.v1alpha1.ListProjectMembersResponse.pagination:type_name -> matrixhub.v1alpha1.Pagination
	2,  // 13: matrixhub.v1alpha1.ProjectMember.member_type:type_name -> matrixhub.v1alpha1.MemberType
	27, // 14: matrixhub.v1alpha1.ProjectMember.role:type_name -> matrixhub.v1alpha1.ProjectRoleType
	2,  // 15: matrixhub.v1alpha1.AddProjectMemberWithRoleRequest.member_type:type_name -> matrixhub.v1alpha1.MemberType
	27, // 16: matrixhub.v1alpha1.AddProjectMemberWithRoleRequest.role:type_name -> matrixhub.v1alpha1.ProjectRoleType
	20, // 17: matrixhub.v1alpha1.RemoveProjectMembersRequest.members:type_name -> matrixhub.v1alpha1.MemberToRemove
	2,  // 18: matrixhub.v1alpha1.MemberToRemove.member_type:type_name -> matrixhub.v1alpha1.MemberType
	2,  // 19: matrixhub.v1alpha1.UpdateProjectMemberRoleRequest.member_type:type_name -> matrixhub.v1alpha1.MemberType
	27, // 20: matrixhub.v1alpha1.UpdateProjectMemberRoleRequest.role:type_name -> matrixhub.v1alpha1.ProjectRoleType
	3,  // 21: matrixhub.v1alpha1.Projects.CreateProject:input_type -> matrixhub.v1alpha1.CreateProjectRequest
	5,  // 22: matrixhub.v1alpha1.Projects.ListProjects:input_type -> matrixhub.v1alpha1.ListProjectsRequest
	7,  // 23: matrixhub.v1alpha1.Projects.GetProject:input_type -> matrixhub.v1alpha1.GetProjectRequest
	11, // 24: matrixhub.v1alpha1.Projects.UpdateProject:input_type -> matrixhub.v1alpha1.UpdateProjectRequest
	9,  // 25: matrixhub.v1alpha1.Projects.DeleteProject:input_type -> matrixhub.v1alpha1.DeleteProjectRequest
	14, // 26: matrixhub.v1alpha1.Projects.ListProjectMembers:input_type -> matrixhub.v1alpha1.ListProjectMembersRequest
	17, // 27: matrixhub.v1alpha1.Projects.AddProjectMemberWithRole:input_type -> matrixhub.v1alpha1.AddProjectMemberWithRoleRequest
	19, // 28: matrixhub.v1alpha1.Projects.RemoveProjectMembers:input_type -> matrixhub.v1alpha1.RemoveProjectMembersRequest
	22, // 29: matrixhub.v1alpha1.Projects.UpdateProjectMemberRole:input_type -> matrixhub.v1alpha1.UpdateProjectMemberRoleRequest
	4,  // 30: matrixhub.v1alpha1.Projects.CreateProject:output_type -> matrixhub.v1alpha1.CreateProjectResponse
	6,  // 31: matrixhub.v1alpha1.Projects.ListProjects:output_type -> matrixhub.v1alpha1.ListProjectsResponse
	8,  // 32: matrixhub.v1alpha1.Projects.GetProject:output_type -> matrixhub.v1alpha1.GetProjectResponse
	12, // 33: matrixhub.v1alpha1.Projects.UpdateProject:output_type -> matrixhub.v1alpha1.UpdateProjectResponse
	10, // 34: matrixhub.v1alpha1.Projects.DeleteProject:output_type -> matrixhub.v1alpha1.DeleteProjectResponse
	15, // 35: matrixhub.v1alpha1.Projects.ListProjectMembers:output_type -> matrixhub.v1alpha1.ListProjectMembersResponse
	18, // 36: matrixhub.v1alpha1.Projects.AddProjectMemberWithRole:output_type -> matrixhub.v1alpha1.AddProjectMemberWithRoleResponse
	21, // 37: matrixhub.v1alpha1.Projects.RemoveProjectMembers:output_type -> matrixhub.v1alpha1.RemoveProjectMembersResponse
	23, // 38: matrixhub.v1alpha1.Projects.UpdateProjectMemberRole:output_type -> matrixhub.v1alpha1.UpdateProjectMemberRoleResponse
	30, // [30:39] is the sub-list for method output_type
	21, // [21:30] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_v1alpha1_project_proto_init() }
func file_v1alpha1_project_proto_init() {
	if File_v1alpha1_project_proto != nil {
		return
	}
	file_v1alpha1_role_proto_init()
	file_v1alpha1_utils_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_project_proto_rawDesc), len(file_v1alpha1_project_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1alpha1_project_proto_goTypes,
		DependencyIndexes: file_v1alpha1_project_proto_depIdxs,
		EnumInfos:         file_v1alpha1_project_proto_enumTypes,
		MessageInfos:      file_v1alpha1_project_proto_msgTypes,
	}.Build()
	File_v1alpha1_project_proto = out.File
	file_v1alpha1_project_proto_goTypes = nil
	file_v1alpha1_project_proto_depIdxs = nil
}
