// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1alpha1/system.proto

package v1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetSystemConfigRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSystemConfigRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSystemConfigRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSystemConfigRequestMultiError, or nil if none found.
func (m *GetSystemConfigRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSystemConfigRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetSystemConfigRequestMultiError(errors)
	}

	return nil
}

// GetSystemConfigRequestMultiError is an error wrapping multiple validation
// errors returned by GetSystemConfigRequest.ValidateAll() if the designated
// constraints aren't met.
type GetSystemConfigRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSystemConfigRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSystemConfigRequestMultiError) AllErrors() []error { return m }

// GetSystemConfigRequestValidationError is the validation error returned by
// GetSystemConfigRequest.Validate if the designated constraints aren't met.
type GetSystemConfigRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSystemConfigRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSystemConfigRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSystemConfigRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSystemConfigRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSystemConfigRequestValidationError) ErrorName() string {
	return "GetSystemConfigRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSystemConfigRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSystemConfigRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSystemConfigRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSystemConfigRequestValidationError{}

// Validate checks the field values on SystemConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SystemConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SystemConfig with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SystemConfigMultiError, or
// nil if none found.
func (m *SystemConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *SystemConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEndpoints()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SystemConfigValidationError{
					field:  "Endpoints",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SystemConfigValidationError{
					field:  "Endpoints",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndpoints()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SystemConfigValidationError{
				field:  "Endpoints",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SystemConfigMultiError(errors)
	}

	return nil
}

// SystemConfigMultiError is an error wrapping multiple validation errors
// returned by SystemConfig.ValidateAll() if the designated constraints aren't met.
type SystemConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SystemConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SystemConfigMultiError) AllErrors() []error { return m }

// SystemConfigValidationError is the validation error returned by
// SystemConfig.Validate if the designated constraints aren't met.
type SystemConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SystemConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SystemConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SystemConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SystemConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SystemConfigValidationError) ErrorName() string { return "SystemConfigValidationError" }

// Error satisfies the builtin error interface
func (e SystemConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSystemConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SystemConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SystemConfigValidationError{}

// Validate checks the field values on Endpoints with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Endpoints) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Endpoints with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EndpointsMultiError, or nil
// if none found.
func (m *Endpoints) ValidateAll() error {
	return m.validate(true)
}

func (m *Endpoints) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for HfBase

	if len(errors) > 0 {
		return EndpointsMultiError(errors)
	}

	return nil
}

// EndpointsMultiError is an error wrapping multiple validation errors returned
// by Endpoints.ValidateAll() if the designated constraints aren't met.
type EndpointsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EndpointsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EndpointsMultiError) AllErrors() []error { return m }

// EndpointsValidationError is the validation error returned by
// Endpoints.Validate if the designated constraints aren't met.
type EndpointsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EndpointsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EndpointsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EndpointsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EndpointsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EndpointsValidationError) ErrorName() string { return "EndpointsValidationError" }

// Error satisfies the builtin error interface
func (e EndpointsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEndpoints.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EndpointsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EndpointsValidationError{}
