// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: v1alpha1/system.proto

package v1alpha1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSystemConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemConfigRequest) Reset() {
	*x = GetSystemConfigRequest{}
	mi := &file_v1alpha1_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemConfigRequest) ProtoMessage() {}

func (x *GetSystemConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemConfigRequest.ProtoReflect.Descriptor instead.
func (*GetSystemConfigRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_system_proto_rawDescGZIP(), []int{0}
}

type SystemConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     *Endpoints             `protobuf:"bytes,1,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemConfig) Reset() {
	*x = SystemConfig{}
	mi := &file_v1alpha1_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemConfig) ProtoMessage() {}

func (x *SystemConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemConfig.ProtoReflect.Descriptor instead.
func (*SystemConfig) Descriptor() ([]byte, []int) {
	return file_v1alpha1_system_proto_rawDescGZIP(), []int{1}
}

func (x *SystemConfig) GetEndpoints() *Endpoints {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// Endpoints are externally-reachable base URLs. The frontend renders
// `HF_ENDPOINT=<hf_base>` on model/dataset detail pages.
type Endpoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HfBase        string                 `protobuf:"bytes,1,opt,name=hf_base,json=hfBase,proto3" json:"hf_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoints) Reset() {
	*x = Endpoints{}
	mi := &file_v1alpha1_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoints) ProtoMessage() {}

func (x *Endpoints) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoints.ProtoReflect.Descriptor instead.
func (*Endpoints) Descriptor() ([]byte, []int) {
	return file_v1alpha1_system_proto_rawDescGZIP(), []int{2}
}

func (x *Endpoints) GetHfBase() string {
	if x != nil {
		return x.HfBase
	}
	return ""
}

var File_v1alpha1_system_proto protoreflect.FileDescriptor

const file_v1alpha1_system_proto_rawDesc = "" +
	"\n" +
	"\x15v1alpha1/system.proto\x12\x12matrixhub.v1alpha1\x1a\x1cgoogle/api/annotations.proto\"\x18\n" +
	"\x16GetSystemConfigRequest\"K\n" +
	"\fSystemConfig\x12;\n" +
	"\tendpoints\x18\x01 \x01(\v2\x1d.matrixhub.v1alpha1.EndpointsR\tendpoints\"$\n" +
	"\tEndpoints\x12\x17\n" +
	"\ahf_base\x18\x01 \x01(\tR\x06hfBase2\x96\x01\n" +
	"\rSystemService\x12\x84\x01\n" +
	"\x0fGetSystemConfig\x12*.matrixhub.v1alpha1.GetSystemConfigRequest\x1a .matrixhub.v1alpha1.SystemConfig\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1alpha1/system/configB<Z:github.com/matrixhub-ai/matrixhub/api/go/v1alpha1;v1alpha1b\x06proto3"

var (
	file_v1alpha1_system_proto_rawDescOnce sync.Once
	file_v1alpha1_system_proto_rawDescData []byte
)

func file_v1alpha1_system_proto_rawDescGZIP() []byte {
	file_v1alpha1_system_proto_rawDescOnce.Do(func() {
		file_v1alpha1_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_system_proto_rawDesc), len(file_v1alpha1_system_proto_rawDesc)))
	})
	return file_v1alpha1_system_proto_rawDescData
}

var file_v1alpha1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1alpha1_system_proto_goTypes = []any{
	(*GetSystemConfigRequest)(nil), // 0: matrixhub.v1alpha1.GetSystemConfigRequest
	(*SystemConfig)(nil),           // 1: matrixhub.v1alpha1.SystemConfig
	(*Endpoints)(nil),              // 2: matrixhub.v1alpha1.Endpoints
}
var file_v1alpha1_system_proto_depIdxs = []int32{
	2, // 0: matrixhub.v1alpha1.SystemConfig.endpoints:type_name -> matrixhub.v1alpha1.Endpoints
	0, // 1: matrixhub.v1alpha1.SystemService.GetSystemConfig:input_type -> matrixhub.v1alpha1.GetSystemConfigRequest
	1, // 2: matrixhub.v1alpha1.SystemService.GetSystemConfig:output_type -> matrixhub.v1alpha1.SystemConfig
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1alpha1_system_proto_init() }
func file_v1alpha1_system_proto_init() {
	if File_v1alpha1_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_system_proto_rawDesc), len(file_v1alpha1_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1alpha1_system_proto_goTypes,
		DependencyIndexes: file_v1alpha1_system_proto_depIdxs,
		MessageInfos:      file_v1alpha1_system_proto_msgTypes,
	}.Build()
	File_v1alpha1_system_proto = out.File
	file_v1alpha1_system_proto_goTypes = nil
	file_v1alpha1_system_proto_depIdxs = nil
}
